name: text_composition
description: A new Flutter package project.
version: 0.0.5
publish_to: none
author: mabdc
homepage: https://github.com/mabDc/text_composition

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
